// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: bs/basestation.proto

package bs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionState int32

const (
	ConnectionState_OFFLINE ConnectionState = 0
	ConnectionState_ONLINE  ConnectionState = 1
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
	}
	ConnectionState_value = map[string]int32{
		"OFFLINE": 0,
		"ONLINE":  1,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_bs_basestation_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_bs_basestation_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{0}
}

type ProtoBasestationState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, hex string
	BsEui string `protobuf:"bytes,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// ConnectionState
	State         ConnectionState `protobuf:"varint,2,opt,name=state,proto3,enum=bs.ConnectionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBasestationState) Reset() {
	*x = ProtoBasestationState{}
	mi := &file_bs_basestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBasestationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBasestationState) ProtoMessage() {}

func (x *ProtoBasestationState) ProtoReflect() protoreflect.Message {
	mi := &file_bs_basestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBasestationState.ProtoReflect.Descriptor instead.
func (*ProtoBasestationState) Descriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoBasestationState) GetBsEui() string {
	if x != nil {
		return x.BsEui
	}
	return ""
}

func (x *ProtoBasestationState) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_OFFLINE
}

type ProtoBasestationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, hex string
	BsEui string `protobuf:"bytes,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Message.
	//
	// Types that are valid to be assigned to V1:
	//
	//	*ProtoBasestationMessage_Con
	//	*ProtoBasestationMessage_Status
	//	*ProtoBasestationMessage_VmStatus
	V1            isProtoBasestationMessage_V1 `protobuf_oneof:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBasestationMessage) Reset() {
	*x = ProtoBasestationMessage{}
	mi := &file_bs_basestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBasestationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBasestationMessage) ProtoMessage() {}

func (x *ProtoBasestationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bs_basestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBasestationMessage.ProtoReflect.Descriptor instead.
func (*ProtoBasestationMessage) Descriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoBasestationMessage) GetBsEui() string {
	if x != nil {
		return x.BsEui
	}
	return ""
}

func (x *ProtoBasestationMessage) GetV1() isProtoBasestationMessage_V1 {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *ProtoBasestationMessage) GetCon() *BasestationConnection {
	if x != nil {
		if x, ok := x.V1.(*ProtoBasestationMessage_Con); ok {
			return x.Con
		}
	}
	return nil
}

func (x *ProtoBasestationMessage) GetStatus() *BasestationStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoBasestationMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ProtoBasestationMessage) GetVmStatus() *BasestationVariableMacStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoBasestationMessage_VmStatus); ok {
			return x.VmStatus
		}
	}
	return nil
}

type isProtoBasestationMessage_V1 interface {
	isProtoBasestationMessage_V1()
}

type ProtoBasestationMessage_Con struct {
	// Connect
	Con *BasestationConnection `protobuf:"bytes,3,opt,name=con,proto3,oneof"`
}

type ProtoBasestationMessage_Status struct {
	// Status
	Status *BasestationStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type ProtoBasestationMessage_VmStatus struct {
	// VM Status
	VmStatus *BasestationVariableMacStatus `protobuf:"bytes,5,opt,name=vm_status,json=vmStatus,proto3,oneof"`
}

func (*ProtoBasestationMessage_Con) isProtoBasestationMessage_V1() {}

func (*ProtoBasestationMessage_Status) isProtoBasestationMessage_V1() {}

func (*ProtoBasestationMessage_VmStatus) isProtoBasestationMessage_V1() {}

// Connect
type BasestationConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix UTC system time
	Ts *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	// Requested protocol version, major.minor.patch
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// True if Base Station is bidirectional
	Bidi bool `protobuf:"varint,4,opt,name=bidi,proto3" json:"bidi,omitempty"`
	// Vendor of the Base Station, optional
	Vendor *string `protobuf:"bytes,5,opt,name=vendor,proto3,oneof" json:"vendor,omitempty"`
	// Model of the Base Station, optional
	Model *string `protobuf:"bytes,6,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// Name of the Base Station, optional
	Name *string `protobuf:"bytes,7,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Software version, optional
	SwVersion     *string `protobuf:"bytes,8,opt,name=sw_version,json=swVersion,proto3,oneof" json:"sw_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationConnection) Reset() {
	*x = BasestationConnection{}
	mi := &file_bs_basestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationConnection) ProtoMessage() {}

func (x *BasestationConnection) ProtoReflect() protoreflect.Message {
	mi := &file_bs_basestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationConnection.ProtoReflect.Descriptor instead.
func (*BasestationConnection) Descriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{2}
}

func (x *BasestationConnection) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BasestationConnection) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BasestationConnection) GetBidi() bool {
	if x != nil {
		return x.Bidi
	}
	return false
}

func (x *BasestationConnection) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *BasestationConnection) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *BasestationConnection) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BasestationConnection) GetSwVersion() string {
	if x != nil && x.SwVersion != nil {
		return *x.SwVersion
	}
	return ""
}

// Status
type BasestationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status code, using POSIX error numbers, 0 for ok
	StatusCode uint32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Status message
	StatusMsg string `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Unix UTC system time
	Ts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	// Fraction of TX time, sliding window over one hour
	DutyCycle float32 `protobuf:"fixed32,5,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	// Geographic location [Latitude, Longitude, Altitude], optional
	GeoLocation *GeoLocation `protobuf:"bytes,6,opt,name=geo_location,json=geoLocation,proto3,oneof" json:"geo_location,omitempty"`
	// System uptime in seconds, optional
	Uptime *uint64 `protobuf:"varint,7,opt,name=uptime,proto3,oneof" json:"uptime,omitempty"`
	// System temperature in degree Celsius, optional
	Temp *float64 `protobuf:"fixed64,8,opt,name=temp,proto3,oneof" json:"temp,omitempty"`
	// CPU utilization, normalized to 1.0 for all cores, optional
	Cpu *float64 `protobuf:"fixed64,9,opt,name=cpu,proto3,oneof" json:"cpu,omitempty"`
	// Memory utilization, normalized to 1.0, optional
	Memory        *float64 `protobuf:"fixed64,10,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationStatus) Reset() {
	*x = BasestationStatus{}
	mi := &file_bs_basestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationStatus) ProtoMessage() {}

func (x *BasestationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bs_basestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationStatus.ProtoReflect.Descriptor instead.
func (*BasestationStatus) Descriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{3}
}

func (x *BasestationStatus) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BasestationStatus) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *BasestationStatus) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BasestationStatus) GetDutyCycle() float32 {
	if x != nil {
		return x.DutyCycle
	}
	return 0
}

func (x *BasestationStatus) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

func (x *BasestationStatus) GetUptime() uint64 {
	if x != nil && x.Uptime != nil {
		return *x.Uptime
	}
	return 0
}

func (x *BasestationStatus) GetTemp() float64 {
	if x != nil && x.Temp != nil {
		return *x.Temp
	}
	return 0
}

func (x *BasestationStatus) GetCpu() float64 {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return 0
}

func (x *BasestationStatus) GetMemory() float64 {
	if x != nil && x.Memory != nil {
		return *x.Memory
	}
	return 0
}

type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float32                `protobuf:"fixed32,3,opt,name=alt,proto3" json:"alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_bs_basestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_bs_basestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{4}
}

func (x *GeoLocation) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoLocation) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoLocation) GetAlt() float32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

// The VM Status represents a list of the activated MAC-Types.
type BasestationVariableMacStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of activated macTypes
	MacTypes      []int64 `protobuf:"varint,2,rep,packed,name=mac_types,json=macTypes,proto3" json:"mac_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationVariableMacStatus) Reset() {
	*x = BasestationVariableMacStatus{}
	mi := &file_bs_basestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationVariableMacStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationVariableMacStatus) ProtoMessage() {}

func (x *BasestationVariableMacStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bs_basestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationVariableMacStatus.ProtoReflect.Descriptor instead.
func (*BasestationVariableMacStatus) Descriptor() ([]byte, []int) {
	return file_bs_basestation_proto_rawDescGZIP(), []int{5}
}

func (x *BasestationVariableMacStatus) GetMacTypes() []int64 {
	if x != nil {
		return x.MacTypes
	}
	return nil
}

var File_bs_basestation_proto protoreflect.FileDescriptor

const file_bs_basestation_proto_rawDesc = "" +
	"\n" +
	"\x14bs/basestation.proto\x12\x02bs\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\x15ProtoBasestationState\x12\x15\n" +
	"\x06bs_eui\x18\x01 \x01(\tR\x05bsEui\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.bs.ConnectionStateR\x05state\"\xd7\x01\n" +
	"\x17ProtoBasestationMessage\x12\x15\n" +
	"\x06bs_eui\x18\x01 \x01(\tR\x05bsEui\x12-\n" +
	"\x03con\x18\x03 \x01(\v2\x19.bs.BasestationConnectionH\x00R\x03con\x12/\n" +
	"\x06status\x18\x04 \x01(\v2\x15.bs.BasestationStatusH\x00R\x06status\x12?\n" +
	"\tvm_status\x18\x05 \x01(\v2 .bs.BasestationVariableMacStatusH\x00R\bvmStatusB\x04\n" +
	"\x02v1\"\x93\x02\n" +
	"\x15BasestationConnection\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04bidi\x18\x04 \x01(\bR\x04bidi\x12\x1b\n" +
	"\x06vendor\x18\x05 \x01(\tH\x00R\x06vendor\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x06 \x01(\tH\x01R\x05model\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\a \x01(\tH\x02R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"sw_version\x18\b \x01(\tH\x03R\tswVersion\x88\x01\x01B\t\n" +
	"\a_vendorB\b\n" +
	"\x06_modelB\a\n" +
	"\x05_nameB\r\n" +
	"\v_sw_version\"\xf9\x02\n" +
	"\x11BasestationStatus\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\rR\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"status_msg\x18\x03 \x01(\tR\tstatusMsg\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1d\n" +
	"\n" +
	"duty_cycle\x18\x05 \x01(\x02R\tdutyCycle\x127\n" +
	"\fgeo_location\x18\x06 \x01(\v2\x0f.bs.GeoLocationH\x00R\vgeoLocation\x88\x01\x01\x12\x1b\n" +
	"\x06uptime\x18\a \x01(\x04H\x01R\x06uptime\x88\x01\x01\x12\x17\n" +
	"\x04temp\x18\b \x01(\x01H\x02R\x04temp\x88\x01\x01\x12\x15\n" +
	"\x03cpu\x18\t \x01(\x01H\x03R\x03cpu\x88\x01\x01\x12\x1b\n" +
	"\x06memory\x18\n" +
	" \x01(\x01H\x04R\x06memory\x88\x01\x01B\x0f\n" +
	"\r_geo_locationB\t\n" +
	"\a_uptimeB\a\n" +
	"\x05_tempB\x06\n" +
	"\x04_cpuB\t\n" +
	"\a_memory\"C\n" +
	"\vGeoLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\x02R\x03alt\";\n" +
	"\x1cBasestationVariableMacStatus\x12\x1b\n" +
	"\tmac_types\x18\x02 \x03(\x03R\bmacTypes**\n" +
	"\x0fConnectionState\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01B\xb0\x01\n" +
	"\x14io.chirpstack.api.bsB\x10BasestationProtoP\x01Z-github.com/chirpstack/splitstack/api/go/v4/bs\xaa\x02\x16Chirpstack.Basestation\xca\x02\x16Chirpstack\\Basestation\xe2\x02\"GPBMetadata\\Chirpstack\\Basestationb\x06proto3"

var (
	file_bs_basestation_proto_rawDescOnce sync.Once
	file_bs_basestation_proto_rawDescData []byte
)

func file_bs_basestation_proto_rawDescGZIP() []byte {
	file_bs_basestation_proto_rawDescOnce.Do(func() {
		file_bs_basestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bs_basestation_proto_rawDesc), len(file_bs_basestation_proto_rawDesc)))
	})
	return file_bs_basestation_proto_rawDescData
}

var file_bs_basestation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bs_basestation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bs_basestation_proto_goTypes = []any{
	(ConnectionState)(0),                 // 0: bs.ConnectionState
	(*ProtoBasestationState)(nil),        // 1: bs.ProtoBasestationState
	(*ProtoBasestationMessage)(nil),      // 2: bs.ProtoBasestationMessage
	(*BasestationConnection)(nil),        // 3: bs.BasestationConnection
	(*BasestationStatus)(nil),            // 4: bs.BasestationStatus
	(*GeoLocation)(nil),                  // 5: bs.GeoLocation
	(*BasestationVariableMacStatus)(nil), // 6: bs.BasestationVariableMacStatus
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_bs_basestation_proto_depIdxs = []int32{
	0, // 0: bs.ProtoBasestationState.state:type_name -> bs.ConnectionState
	3, // 1: bs.ProtoBasestationMessage.con:type_name -> bs.BasestationConnection
	4, // 2: bs.ProtoBasestationMessage.status:type_name -> bs.BasestationStatus
	6, // 3: bs.ProtoBasestationMessage.vm_status:type_name -> bs.BasestationVariableMacStatus
	7, // 4: bs.BasestationConnection.ts:type_name -> google.protobuf.Timestamp
	7, // 5: bs.BasestationStatus.ts:type_name -> google.protobuf.Timestamp
	5, // 6: bs.BasestationStatus.geo_location:type_name -> bs.GeoLocation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_bs_basestation_proto_init() }
func file_bs_basestation_proto_init() {
	if File_bs_basestation_proto != nil {
		return
	}
	file_bs_basestation_proto_msgTypes[1].OneofWrappers = []any{
		(*ProtoBasestationMessage_Con)(nil),
		(*ProtoBasestationMessage_Status)(nil),
		(*ProtoBasestationMessage_VmStatus)(nil),
	}
	file_bs_basestation_proto_msgTypes[2].OneofWrappers = []any{}
	file_bs_basestation_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bs_basestation_proto_rawDesc), len(file_bs_basestation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bs_basestation_proto_goTypes,
		DependencyIndexes: file_bs_basestation_proto_depIdxs,
		EnumInfos:         file_bs_basestation_proto_enumTypes,
		MessageInfos:      file_bs_basestation_proto_msgTypes,
	}.Build()
	File_bs_basestation_proto = out.File
	file_bs_basestation_proto_goTypes = nil
	file_bs_basestation_proto_depIdxs = nil
}
