// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: bs/cmd.proto

package bs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, hex string
	BsEui string `protobuf:"bytes,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Types that are valid to be assigned to V1:
	//
	//	*ProtoCommand_DlDataQue
	//	*ProtoCommand_DlDataRev
	//	*ProtoCommand_DlRxStatQry
	//	*ProtoCommand_AttPrp
	//	*ProtoCommand_DetPrp
	//	*ProtoCommand_ReqStatus
	//	*ProtoCommand_VmActivate
	//	*ProtoCommand_VmDeactivate
	//	*ProtoCommand_VmStatus
	V1            isProtoCommand_V1 `protobuf_oneof:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoCommand) Reset() {
	*x = ProtoCommand{}
	mi := &file_bs_cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCommand) ProtoMessage() {}

func (x *ProtoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCommand.ProtoReflect.Descriptor instead.
func (*ProtoCommand) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoCommand) GetBsEui() string {
	if x != nil {
		return x.BsEui
	}
	return ""
}

func (x *ProtoCommand) GetV1() isProtoCommand_V1 {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *ProtoCommand) GetDlDataQue() *EnqueDownlink {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DlDataQue); ok {
			return x.DlDataQue
		}
	}
	return nil
}

func (x *ProtoCommand) GetDlDataRev() *RevokeDownlink {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DlDataRev); ok {
			return x.DlDataRev
		}
	}
	return nil
}

func (x *ProtoCommand) GetDlRxStatQry() *DownlinkRxStatusQuery {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DlRxStatQry); ok {
			return x.DlRxStatQry
		}
	}
	return nil
}

func (x *ProtoCommand) GetAttPrp() *AttachPropagate {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_AttPrp); ok {
			return x.AttPrp
		}
	}
	return nil
}

func (x *ProtoCommand) GetDetPrp() *DetachPropagate {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DetPrp); ok {
			return x.DetPrp
		}
	}
	return nil
}

func (x *ProtoCommand) GetReqStatus() *RequestStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_ReqStatus); ok {
			return x.ReqStatus
		}
	}
	return nil
}

func (x *ProtoCommand) GetVmActivate() *EnableVariableMac {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_VmActivate); ok {
			return x.VmActivate
		}
	}
	return nil
}

func (x *ProtoCommand) GetVmDeactivate() *DisableVariableMac {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_VmDeactivate); ok {
			return x.VmDeactivate
		}
	}
	return nil
}

func (x *ProtoCommand) GetVmStatus() *RequestVariableMacStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_VmStatus); ok {
			return x.VmStatus
		}
	}
	return nil
}

type isProtoCommand_V1 interface {
	isProtoCommand_V1()
}

type ProtoCommand_DlDataQue struct {
	// Enque downlink
	DlDataQue *EnqueDownlink `protobuf:"bytes,3,opt,name=dl_data_que,json=dlDataQue,proto3,oneof"`
}

type ProtoCommand_DlDataRev struct {
	// Revoke downlink
	DlDataRev *RevokeDownlink `protobuf:"bytes,4,opt,name=dl_data_rev,json=dlDataRev,proto3,oneof"`
}

type ProtoCommand_DlRxStatQry struct {
	// Downlink RX status query
	DlRxStatQry *DownlinkRxStatusQuery `protobuf:"bytes,5,opt,name=dl_rx_stat_qry,json=dlRxStatQry,proto3,oneof"`
}

type ProtoCommand_AttPrp struct {
	// Propagate attach
	AttPrp *AttachPropagate `protobuf:"bytes,6,opt,name=att_prp,json=attPrp,proto3,oneof"`
}

type ProtoCommand_DetPrp struct {
	// Propagate detach
	DetPrp *DetachPropagate `protobuf:"bytes,7,opt,name=det_prp,json=detPrp,proto3,oneof"`
}

type ProtoCommand_ReqStatus struct {
	// Status
	ReqStatus *RequestStatus `protobuf:"bytes,8,opt,name=req_status,json=reqStatus,proto3,oneof"`
}

type ProtoCommand_VmActivate struct {
	// VM Activate
	VmActivate *EnableVariableMac `protobuf:"bytes,9,opt,name=vm_activate,json=vmActivate,proto3,oneof"`
}

type ProtoCommand_VmDeactivate struct {
	// VM Deactivate
	VmDeactivate *DisableVariableMac `protobuf:"bytes,10,opt,name=vm_deactivate,json=vmDeactivate,proto3,oneof"`
}

type ProtoCommand_VmStatus struct {
	// VM Status
	VmStatus *RequestVariableMacStatus `protobuf:"bytes,11,opt,name=vm_status,json=vmStatus,proto3,oneof"`
}

func (*ProtoCommand_DlDataQue) isProtoCommand_V1() {}

func (*ProtoCommand_DlDataRev) isProtoCommand_V1() {}

func (*ProtoCommand_DlRxStatQry) isProtoCommand_V1() {}

func (*ProtoCommand_AttPrp) isProtoCommand_V1() {}

func (*ProtoCommand_DetPrp) isProtoCommand_V1() {}

func (*ProtoCommand_ReqStatus) isProtoCommand_V1() {}

func (*ProtoCommand_VmActivate) isProtoCommand_V1() {}

func (*ProtoCommand_VmDeactivate) isProtoCommand_V1() {}

func (*ProtoCommand_VmStatus) isProtoCommand_V1() {}

// Downlink data queue
type EnqueDownlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui string `protobuf:"bytes,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// Assigned queue ID for reference
	DlQueId uint64 `protobuf:"varint,3,opt,name=dl_que_id,json=dlQueId,proto3" json:"dl_que_id,omitempty"`
	// Priority, higher values are prioritized, optional, default 0
	Priority *float32 `protobuf:"fixed32,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// MPF header byte, 1 byte
	Format *uint32 `protobuf:"varint,5,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// Downlink payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*EnqueDownlink_Ack
	//	*EnqueDownlink_Data
	//	*EnqueDownlink_DataEnc
	Payload isEnqueDownlink_Payload `protobuf_oneof:"payload"`
	// True to request End Point response, optional
	ResponseExp *bool `protobuf:"varint,9,opt,name=response_exp,json=responseExp,proto3,oneof" json:"response_exp,omitempty"`
	// True to request priority End Point response, optional
	ResponsePrio *bool `protobuf:"varint,10,opt,name=response_prio,json=responsePrio,proto3,oneof" json:"response_prio,omitempty"`
	// True to request further End Point DL window, optional
	ReqDlWindow *bool `protobuf:"varint,11,opt,name=req_dl_window,json=reqDlWindow,proto3,oneof" json:"req_dl_window,omitempty"`
	// True to send downlink only if End Point expects a response, optional
	OnlyIfExpected *bool `protobuf:"varint,12,opt,name=only_if_expected,json=onlyIfExpected,proto3,oneof" json:"only_if_expected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueDownlink) Reset() {
	*x = EnqueDownlink{}
	mi := &file_bs_cmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueDownlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueDownlink) ProtoMessage() {}

func (x *EnqueDownlink) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueDownlink.ProtoReflect.Descriptor instead.
func (*EnqueDownlink) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueDownlink) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

func (x *EnqueDownlink) GetDlQueId() uint64 {
	if x != nil {
		return x.DlQueId
	}
	return 0
}

func (x *EnqueDownlink) GetPriority() float32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *EnqueDownlink) GetFormat() uint32 {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return 0
}

func (x *EnqueDownlink) GetPayload() isEnqueDownlink_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueDownlink) GetAck() *Acknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *EnqueDownlink) GetData() *DownlinkData {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *EnqueDownlink) GetDataEnc() *DownlinkDataEncrypted {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_DataEnc); ok {
			return x.DataEnc
		}
	}
	return nil
}

func (x *EnqueDownlink) GetResponseExp() bool {
	if x != nil && x.ResponseExp != nil {
		return *x.ResponseExp
	}
	return false
}

func (x *EnqueDownlink) GetResponsePrio() bool {
	if x != nil && x.ResponsePrio != nil {
		return *x.ResponsePrio
	}
	return false
}

func (x *EnqueDownlink) GetReqDlWindow() bool {
	if x != nil && x.ReqDlWindow != nil {
		return *x.ReqDlWindow
	}
	return false
}

func (x *EnqueDownlink) GetOnlyIfExpected() bool {
	if x != nil && x.OnlyIfExpected != nil {
		return *x.OnlyIfExpected
	}
	return false
}

type isEnqueDownlink_Payload interface {
	isEnqueDownlink_Payload()
}

type EnqueDownlink_Ack struct {
	// Uplink acknowledgement
	Ack *Acknowledgement `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type EnqueDownlink_Data struct {
	// Unencrypted payload
	Data *DownlinkData `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
}

type EnqueDownlink_DataEnc struct {
	// Encrypted payload
	DataEnc *DownlinkDataEncrypted `protobuf:"bytes,8,opt,name=data_enc,json=dataEnc,proto3,oneof"`
}

func (*EnqueDownlink_Ack) isEnqueDownlink_Payload() {}

func (*EnqueDownlink_Data) isEnqueDownlink_Payload() {}

func (*EnqueDownlink_DataEnc) isEnqueDownlink_Payload() {}

// Uplink acknowledgement
type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_bs_cmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{2}
}

// Unencrypted payload
type DownlinkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User data
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkData) Reset() {
	*x = DownlinkData{}
	mi := &file_bs_cmd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkData) ProtoMessage() {}

func (x *DownlinkData) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkData.ProtoReflect.Descriptor instead.
func (*DownlinkData) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *DownlinkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Encrypted payload
type DownlinkDataEncrypted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data for each of the m packet counters
	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Endnode packet counter for which the respective data entry is valid
	PacketCnt     []uint32 `protobuf:"varint,2,rep,packed,name=packet_cnt,json=packetCnt,proto3" json:"packet_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkDataEncrypted) Reset() {
	*x = DownlinkDataEncrypted{}
	mi := &file_bs_cmd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkDataEncrypted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkDataEncrypted) ProtoMessage() {}

func (x *DownlinkDataEncrypted) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkDataEncrypted.ProtoReflect.Descriptor instead.
func (*DownlinkDataEncrypted) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *DownlinkDataEncrypted) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownlinkDataEncrypted) GetPacketCnt() []uint32 {
	if x != nil {
		return x.PacketCnt
	}
	return nil
}

// Downlink data revoke
type RevokeDownlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui string `protobuf:"bytes,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// Assigned queue ID for reference
	DlQueId       uint64 `protobuf:"varint,3,opt,name=dl_que_id,json=dlQueId,proto3" json:"dl_que_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDownlink) Reset() {
	*x = RevokeDownlink{}
	mi := &file_bs_cmd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDownlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDownlink) ProtoMessage() {}

func (x *RevokeDownlink) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDownlink.ProtoReflect.Descriptor instead.
func (*RevokeDownlink) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeDownlink) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

func (x *RevokeDownlink) GetDlQueId() uint64 {
	if x != nil {
		return x.DlQueId
	}
	return 0
}

// Downlink rx status query
type DownlinkRxStatusQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui    string `protobuf:"bytes,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkRxStatusQuery) Reset() {
	*x = DownlinkRxStatusQuery{}
	mi := &file_bs_cmd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkRxStatusQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkRxStatusQuery) ProtoMessage() {}

func (x *DownlinkRxStatusQuery) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkRxStatusQuery.ProtoReflect.Descriptor instead.
func (*DownlinkRxStatusQuery) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{6}
}

func (x *DownlinkRxStatusQuery) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

type AttachPropagate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui string `protobuf:"bytes,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// End Point short address
	ShAddr uint32 `protobuf:"varint,3,opt,name=sh_addr,json=shAddr,proto3" json:"sh_addr,omitempty"`
	// 16 Byte End Point network session key
	NwkSessionKey []byte `protobuf:"bytes,4,opt,name=nwk_session_key,json=nwkSessionKey,proto3" json:"nwk_session_key,omitempty"`
	// Packet counter.
	LastPacketCnt int32 `protobuf:"varint,5,opt,name=last_packet_cnt,json=lastPacketCnt,proto3" json:"last_packet_cnt,omitempty"`
	// True if End Point is bidirectional
	Bidi bool `protobuf:"varint,6,opt,name=bidi,proto3" json:"bidi,omitempty"`
	// True if End Point uses dual channel mode
	DualChannel bool `protobuf:"varint,7,opt,name=dual_channel,json=dualChannel,proto3" json:"dual_channel,omitempty"`
	// True if End Point uses DL repetition
	Repetition bool `protobuf:"varint,8,opt,name=repetition,proto3" json:"repetition,omitempty"`
	// True if End Point uses wide carrier offset
	WideCarrOff bool `protobuf:"varint,9,opt,name=wide_carr_off,json=wideCarrOff,proto3" json:"wide_carr_off,omitempty"`
	// True if End Point uses long DL interblock distance
	LongBlkDist   bool `protobuf:"varint,10,opt,name=long_blk_dist,json=longBlkDist,proto3" json:"long_blk_dist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPropagate) Reset() {
	*x = AttachPropagate{}
	mi := &file_bs_cmd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPropagate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPropagate) ProtoMessage() {}

func (x *AttachPropagate) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPropagate.ProtoReflect.Descriptor instead.
func (*AttachPropagate) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{7}
}

func (x *AttachPropagate) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

func (x *AttachPropagate) GetShAddr() uint32 {
	if x != nil {
		return x.ShAddr
	}
	return 0
}

func (x *AttachPropagate) GetNwkSessionKey() []byte {
	if x != nil {
		return x.NwkSessionKey
	}
	return nil
}

func (x *AttachPropagate) GetLastPacketCnt() int32 {
	if x != nil {
		return x.LastPacketCnt
	}
	return 0
}

func (x *AttachPropagate) GetBidi() bool {
	if x != nil {
		return x.Bidi
	}
	return false
}

func (x *AttachPropagate) GetDualChannel() bool {
	if x != nil {
		return x.DualChannel
	}
	return false
}

func (x *AttachPropagate) GetRepetition() bool {
	if x != nil {
		return x.Repetition
	}
	return false
}

func (x *AttachPropagate) GetWideCarrOff() bool {
	if x != nil {
		return x.WideCarrOff
	}
	return false
}

func (x *AttachPropagate) GetLongBlkDist() bool {
	if x != nil {
		return x.LongBlkDist
	}
	return false
}

type DetachPropagate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui    string `protobuf:"bytes,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachPropagate) Reset() {
	*x = DetachPropagate{}
	mi := &file_bs_cmd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPropagate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPropagate) ProtoMessage() {}

func (x *DetachPropagate) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPropagate.ProtoReflect.Descriptor instead.
func (*DetachPropagate) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{8}
}

func (x *DetachPropagate) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

type RequestStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStatus) Reset() {
	*x = RequestStatus{}
	mi := &file_bs_cmd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStatus) ProtoMessage() {}

func (x *RequestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStatus.ProtoReflect.Descriptor instead.
func (*RequestStatus) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{9}
}

type EnableVariableMac struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MAC-Type of the intended Variable MAC
	MacType       int64 `protobuf:"varint,2,opt,name=mac_type,json=macType,proto3" json:"mac_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableVariableMac) Reset() {
	*x = EnableVariableMac{}
	mi := &file_bs_cmd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableVariableMac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableVariableMac) ProtoMessage() {}

func (x *EnableVariableMac) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableVariableMac.ProtoReflect.Descriptor instead.
func (*EnableVariableMac) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{10}
}

func (x *EnableVariableMac) GetMacType() int64 {
	if x != nil {
		return x.MacType
	}
	return 0
}

type DisableVariableMac struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MAC-Type of the intended Variable MAC
	MacType       int64 `protobuf:"varint,2,opt,name=mac_type,json=macType,proto3" json:"mac_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableVariableMac) Reset() {
	*x = DisableVariableMac{}
	mi := &file_bs_cmd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableVariableMac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableVariableMac) ProtoMessage() {}

func (x *DisableVariableMac) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableVariableMac.ProtoReflect.Descriptor instead.
func (*DisableVariableMac) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{11}
}

func (x *DisableVariableMac) GetMacType() int64 {
	if x != nil {
		return x.MacType
	}
	return 0
}

type RequestVariableMacStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVariableMacStatus) Reset() {
	*x = RequestVariableMacStatus{}
	mi := &file_bs_cmd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVariableMacStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVariableMacStatus) ProtoMessage() {}

func (x *RequestVariableMacStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bs_cmd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVariableMacStatus.ProtoReflect.Descriptor instead.
func (*RequestVariableMacStatus) Descriptor() ([]byte, []int) {
	return file_bs_cmd_proto_rawDescGZIP(), []int{12}
}

var File_bs_cmd_proto protoreflect.FileDescriptor

const file_bs_cmd_proto_rawDesc = "" +
	"\n" +
	"\fbs/cmd.proto\x12\x02bs\"\xa2\x04\n" +
	"\fProtoCommand\x12\x15\n" +
	"\x06bs_eui\x18\x01 \x01(\tR\x05bsEui\x123\n" +
	"\vdl_data_que\x18\x03 \x01(\v2\x11.bs.EnqueDownlinkH\x00R\tdlDataQue\x124\n" +
	"\vdl_data_rev\x18\x04 \x01(\v2\x12.bs.RevokeDownlinkH\x00R\tdlDataRev\x12@\n" +
	"\x0edl_rx_stat_qry\x18\x05 \x01(\v2\x19.bs.DownlinkRxStatusQueryH\x00R\vdlRxStatQry\x12.\n" +
	"\aatt_prp\x18\x06 \x01(\v2\x13.bs.AttachPropagateH\x00R\x06attPrp\x12.\n" +
	"\adet_prp\x18\a \x01(\v2\x13.bs.DetachPropagateH\x00R\x06detPrp\x122\n" +
	"\n" +
	"req_status\x18\b \x01(\v2\x11.bs.RequestStatusH\x00R\treqStatus\x128\n" +
	"\vvm_activate\x18\t \x01(\v2\x15.bs.EnableVariableMacH\x00R\n" +
	"vmActivate\x12=\n" +
	"\rvm_deactivate\x18\n" +
	" \x01(\v2\x16.bs.DisableVariableMacH\x00R\fvmDeactivate\x12;\n" +
	"\tvm_status\x18\v \x01(\v2\x1c.bs.RequestVariableMacStatusH\x00R\bvmStatusB\x04\n" +
	"\x02v1\"\xaa\x04\n" +
	"\rEnqueDownlink\x12\x1f\n" +
	"\vendnode_eui\x18\x02 \x01(\tR\n" +
	"endnodeEui\x12\x1a\n" +
	"\tdl_que_id\x18\x03 \x01(\x04R\adlQueId\x12\x1f\n" +
	"\bpriority\x18\x04 \x01(\x02H\x01R\bpriority\x88\x01\x01\x12\x1b\n" +
	"\x06format\x18\x05 \x01(\rH\x02R\x06format\x88\x01\x01\x12'\n" +
	"\x03ack\x18\x06 \x01(\v2\x13.bs.AcknowledgementH\x00R\x03ack\x12&\n" +
	"\x04data\x18\a \x01(\v2\x10.bs.DownlinkDataH\x00R\x04data\x126\n" +
	"\bdata_enc\x18\b \x01(\v2\x19.bs.DownlinkDataEncryptedH\x00R\adataEnc\x12&\n" +
	"\fresponse_exp\x18\t \x01(\bH\x03R\vresponseExp\x88\x01\x01\x12(\n" +
	"\rresponse_prio\x18\n" +
	" \x01(\bH\x04R\fresponsePrio\x88\x01\x01\x12'\n" +
	"\rreq_dl_window\x18\v \x01(\bH\x05R\vreqDlWindow\x88\x01\x01\x12-\n" +
	"\x10only_if_expected\x18\f \x01(\bH\x06R\x0eonlyIfExpected\x88\x01\x01B\t\n" +
	"\apayloadB\v\n" +
	"\t_priorityB\t\n" +
	"\a_formatB\x0f\n" +
	"\r_response_expB\x10\n" +
	"\x0e_response_prioB\x10\n" +
	"\x0e_req_dl_windowB\x13\n" +
	"\x11_only_if_expected\"\x11\n" +
	"\x0fAcknowledgement\"\"\n" +
	"\fDownlinkData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"J\n" +
	"\x15DownlinkDataEncrypted\x12\x12\n" +
	"\x04data\x18\x01 \x03(\fR\x04data\x12\x1d\n" +
	"\n" +
	"packet_cnt\x18\x02 \x03(\rR\tpacketCnt\"M\n" +
	"\x0eRevokeDownlink\x12\x1f\n" +
	"\vendnode_eui\x18\x02 \x01(\tR\n" +
	"endnodeEui\x12\x1a\n" +
	"\tdl_que_id\x18\x03 \x01(\x04R\adlQueId\"8\n" +
	"\x15DownlinkRxStatusQuery\x12\x1f\n" +
	"\vendnode_eui\x18\x02 \x01(\tR\n" +
	"endnodeEui\"\xba\x02\n" +
	"\x0fAttachPropagate\x12\x1f\n" +
	"\vendnode_eui\x18\x02 \x01(\tR\n" +
	"endnodeEui\x12\x17\n" +
	"\ash_addr\x18\x03 \x01(\rR\x06shAddr\x12&\n" +
	"\x0fnwk_session_key\x18\x04 \x01(\fR\rnwkSessionKey\x12&\n" +
	"\x0flast_packet_cnt\x18\x05 \x01(\x05R\rlastPacketCnt\x12\x12\n" +
	"\x04bidi\x18\x06 \x01(\bR\x04bidi\x12!\n" +
	"\fdual_channel\x18\a \x01(\bR\vdualChannel\x12\x1e\n" +
	"\n" +
	"repetition\x18\b \x01(\bR\n" +
	"repetition\x12\"\n" +
	"\rwide_carr_off\x18\t \x01(\bR\vwideCarrOff\x12\"\n" +
	"\rlong_blk_dist\x18\n" +
	" \x01(\bR\vlongBlkDist\"2\n" +
	"\x0fDetachPropagate\x12\x1f\n" +
	"\vendnode_eui\x18\x02 \x01(\tR\n" +
	"endnodeEui\"\x0f\n" +
	"\rRequestStatus\".\n" +
	"\x11EnableVariableMac\x12\x19\n" +
	"\bmac_type\x18\x02 \x01(\x03R\amacType\"/\n" +
	"\x12DisableVariableMac\x12\x19\n" +
	"\bmac_type\x18\x02 \x01(\x03R\amacType\"\x1a\n" +
	"\x18RequestVariableMacStatusB\xb0\x01\n" +
	"\x14io.chirpstack.api.bsB\x10BasestationProtoP\x01Z-github.com/chirpstack/splitstack/api/go/v4/bs\xaa\x02\x16Chirpstack.Basestation\xca\x02\x16Chirpstack\\Basestation\xe2\x02\"GPBMetadata\\Chirpstack\\Basestationb\x06proto3"

var (
	file_bs_cmd_proto_rawDescOnce sync.Once
	file_bs_cmd_proto_rawDescData []byte
)

func file_bs_cmd_proto_rawDescGZIP() []byte {
	file_bs_cmd_proto_rawDescOnce.Do(func() {
		file_bs_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bs_cmd_proto_rawDesc), len(file_bs_cmd_proto_rawDesc)))
	})
	return file_bs_cmd_proto_rawDescData
}

var file_bs_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bs_cmd_proto_goTypes = []any{
	(*ProtoCommand)(nil),             // 0: bs.ProtoCommand
	(*EnqueDownlink)(nil),            // 1: bs.EnqueDownlink
	(*Acknowledgement)(nil),          // 2: bs.Acknowledgement
	(*DownlinkData)(nil),             // 3: bs.DownlinkData
	(*DownlinkDataEncrypted)(nil),    // 4: bs.DownlinkDataEncrypted
	(*RevokeDownlink)(nil),           // 5: bs.RevokeDownlink
	(*DownlinkRxStatusQuery)(nil),    // 6: bs.DownlinkRxStatusQuery
	(*AttachPropagate)(nil),          // 7: bs.AttachPropagate
	(*DetachPropagate)(nil),          // 8: bs.DetachPropagate
	(*RequestStatus)(nil),            // 9: bs.RequestStatus
	(*EnableVariableMac)(nil),        // 10: bs.EnableVariableMac
	(*DisableVariableMac)(nil),       // 11: bs.DisableVariableMac
	(*RequestVariableMacStatus)(nil), // 12: bs.RequestVariableMacStatus
}
var file_bs_cmd_proto_depIdxs = []int32{
	1,  // 0: bs.ProtoCommand.dl_data_que:type_name -> bs.EnqueDownlink
	5,  // 1: bs.ProtoCommand.dl_data_rev:type_name -> bs.RevokeDownlink
	6,  // 2: bs.ProtoCommand.dl_rx_stat_qry:type_name -> bs.DownlinkRxStatusQuery
	7,  // 3: bs.ProtoCommand.att_prp:type_name -> bs.AttachPropagate
	8,  // 4: bs.ProtoCommand.det_prp:type_name -> bs.DetachPropagate
	9,  // 5: bs.ProtoCommand.req_status:type_name -> bs.RequestStatus
	10, // 6: bs.ProtoCommand.vm_activate:type_name -> bs.EnableVariableMac
	11, // 7: bs.ProtoCommand.vm_deactivate:type_name -> bs.DisableVariableMac
	12, // 8: bs.ProtoCommand.vm_status:type_name -> bs.RequestVariableMacStatus
	2,  // 9: bs.EnqueDownlink.ack:type_name -> bs.Acknowledgement
	3,  // 10: bs.EnqueDownlink.data:type_name -> bs.DownlinkData
	4,  // 11: bs.EnqueDownlink.data_enc:type_name -> bs.DownlinkDataEncrypted
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_bs_cmd_proto_init() }
func file_bs_cmd_proto_init() {
	if File_bs_cmd_proto != nil {
		return
	}
	file_bs_cmd_proto_msgTypes[0].OneofWrappers = []any{
		(*ProtoCommand_DlDataQue)(nil),
		(*ProtoCommand_DlDataRev)(nil),
		(*ProtoCommand_DlRxStatQry)(nil),
		(*ProtoCommand_AttPrp)(nil),
		(*ProtoCommand_DetPrp)(nil),
		(*ProtoCommand_ReqStatus)(nil),
		(*ProtoCommand_VmActivate)(nil),
		(*ProtoCommand_VmDeactivate)(nil),
		(*ProtoCommand_VmStatus)(nil),
	}
	file_bs_cmd_proto_msgTypes[1].OneofWrappers = []any{
		(*EnqueDownlink_Ack)(nil),
		(*EnqueDownlink_Data)(nil),
		(*EnqueDownlink_DataEnc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bs_cmd_proto_rawDesc), len(file_bs_cmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bs_cmd_proto_goTypes,
		DependencyIndexes: file_bs_cmd_proto_depIdxs,
		MessageInfos:      file_bs_cmd_proto_msgTypes,
	}.Build()
	File_bs_cmd_proto = out.File
	file_bs_cmd_proto_goTypes = nil
	file_bs_cmd_proto_depIdxs = nil
}
