// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: bs/rsp.proto

package bs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the current operation
	OpId int64 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// Basestation EUI, hex string
	BsEui string `protobuf:"bytes,2,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Command.
	//
	// Types that are valid to be assigned to V1:
	//
	//	*ProtoResponse_AttRsp
	//	*ProtoResponse_DetRsp
	//	*ProtoResponse_Err
	V1            isProtoResponse_V1 `protobuf_oneof:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoResponse) Reset() {
	*x = ProtoResponse{}
	mi := &file_bs_rsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponse) ProtoMessage() {}

func (x *ProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bs_rsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponse.ProtoReflect.Descriptor instead.
func (*ProtoResponse) Descriptor() ([]byte, []int) {
	return file_bs_rsp_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoResponse) GetOpId() int64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *ProtoResponse) GetBsEui() string {
	if x != nil {
		return x.BsEui
	}
	return ""
}

func (x *ProtoResponse) GetV1() isProtoResponse_V1 {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *ProtoResponse) GetAttRsp() *EndnodeAttachResponse {
	if x != nil {
		if x, ok := x.V1.(*ProtoResponse_AttRsp); ok {
			return x.AttRsp
		}
	}
	return nil
}

func (x *ProtoResponse) GetDetRsp() *EndnodeDetachResponse {
	if x != nil {
		if x, ok := x.V1.(*ProtoResponse_DetRsp); ok {
			return x.DetRsp
		}
	}
	return nil
}

func (x *ProtoResponse) GetErr() *ErrorResponse {
	if x != nil {
		if x, ok := x.V1.(*ProtoResponse_Err); ok {
			return x.Err
		}
	}
	return nil
}

type isProtoResponse_V1 interface {
	isProtoResponse_V1()
}

type ProtoResponse_AttRsp struct {
	// Server attachment
	AttRsp *EndnodeAttachResponse `protobuf:"bytes,4,opt,name=att_rsp,json=attRsp,proto3,oneof"`
}

type ProtoResponse_DetRsp struct {
	// Server detachment
	DetRsp *EndnodeDetachResponse `protobuf:"bytes,5,opt,name=det_rsp,json=detRsp,proto3,oneof"`
}

type ProtoResponse_Err struct {
	Err *ErrorResponse `protobuf:"bytes,6,opt,name=err,proto3,oneof"`
}

func (*ProtoResponse_AttRsp) isProtoResponse_V1() {}

func (*ProtoResponse_DetRsp) isProtoResponse_V1() {}

func (*ProtoResponse_Err) isProtoResponse_V1() {}

type EndnodeAttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui string `protobuf:"bytes,1,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// End Point short address, only if not assigned by the Base Station
	ShAddr *uint32 `protobuf:"varint,2,opt,name=sh_addr,json=shAddr,proto3,oneof" json:"sh_addr,omitempty"`
	// 16 Byte End Point network session key
	NwkSessionKey []byte `protobuf:"bytes,3,opt,name=nwk_session_key,json=nwkSessionKey,proto3" json:"nwk_session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndnodeAttachResponse) Reset() {
	*x = EndnodeAttachResponse{}
	mi := &file_bs_rsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndnodeAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndnodeAttachResponse) ProtoMessage() {}

func (x *EndnodeAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bs_rsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndnodeAttachResponse.ProtoReflect.Descriptor instead.
func (*EndnodeAttachResponse) Descriptor() ([]byte, []int) {
	return file_bs_rsp_proto_rawDescGZIP(), []int{1}
}

func (x *EndnodeAttachResponse) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

func (x *EndnodeAttachResponse) GetShAddr() uint32 {
	if x != nil && x.ShAddr != nil {
		return *x.ShAddr
	}
	return 0
}

func (x *EndnodeAttachResponse) GetNwkSessionKey() []byte {
	if x != nil {
		return x.NwkSessionKey
	}
	return nil
}

type EndnodeDetachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, hex string
	EndnodeEui string `protobuf:"bytes,1,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// End Point signature, 4 bytes little endian
	Sign          uint32 `protobuf:"varint,2,opt,name=sign,proto3" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndnodeDetachResponse) Reset() {
	*x = EndnodeDetachResponse{}
	mi := &file_bs_rsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndnodeDetachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndnodeDetachResponse) ProtoMessage() {}

func (x *EndnodeDetachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bs_rsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndnodeDetachResponse.ProtoReflect.Descriptor instead.
func (*EndnodeDetachResponse) Descriptor() ([]byte, []int) {
	return file_bs_rsp_proto_rawDescGZIP(), []int{2}
}

func (x *EndnodeDetachResponse) GetEndnodeEui() string {
	if x != nil {
		return x.EndnodeEui
	}
	return ""
}

func (x *EndnodeDetachResponse) GetSign() uint32 {
	if x != nil {
		return x.Sign
	}
	return 0
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_bs_rsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bs_rsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_bs_rsp_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bs_rsp_proto protoreflect.FileDescriptor

const file_bs_rsp_proto_rawDesc = "" +
	"\n" +
	"\fbs/rsp.proto\x12\x02bs\"\xd4\x01\n" +
	"\rProtoResponse\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\x03R\x04opId\x12\x15\n" +
	"\x06bs_eui\x18\x02 \x01(\tR\x05bsEui\x124\n" +
	"\aatt_rsp\x18\x04 \x01(\v2\x19.bs.EndnodeAttachResponseH\x00R\x06attRsp\x124\n" +
	"\adet_rsp\x18\x05 \x01(\v2\x19.bs.EndnodeDetachResponseH\x00R\x06detRsp\x12%\n" +
	"\x03err\x18\x06 \x01(\v2\x11.bs.ErrorResponseH\x00R\x03errB\x04\n" +
	"\x02v1\"\x8a\x01\n" +
	"\x15EndnodeAttachResponse\x12\x1f\n" +
	"\vendnode_eui\x18\x01 \x01(\tR\n" +
	"endnodeEui\x12\x1c\n" +
	"\ash_addr\x18\x02 \x01(\rH\x00R\x06shAddr\x88\x01\x01\x12&\n" +
	"\x0fnwk_session_key\x18\x03 \x01(\fR\rnwkSessionKeyB\n" +
	"\n" +
	"\b_sh_addr\"L\n" +
	"\x15EndnodeDetachResponse\x12\x1f\n" +
	"\vendnode_eui\x18\x01 \x01(\tR\n" +
	"endnodeEui\x12\x12\n" +
	"\x04sign\x18\x02 \x01(\rR\x04sign\")\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\xb0\x01\n" +
	"\x14io.chirpstack.api.bsB\x10BasestationProtoP\x01Z-github.com/chirpstack/splitstack/api/go/v4/bs\xaa\x02\x16Chirpstack.Basestation\xca\x02\x16Chirpstack\\Basestation\xe2\x02\"GPBMetadata\\Chirpstack\\Basestationb\x06proto3"

var (
	file_bs_rsp_proto_rawDescOnce sync.Once
	file_bs_rsp_proto_rawDescData []byte
)

func file_bs_rsp_proto_rawDescGZIP() []byte {
	file_bs_rsp_proto_rawDescOnce.Do(func() {
		file_bs_rsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bs_rsp_proto_rawDesc), len(file_bs_rsp_proto_rawDesc)))
	})
	return file_bs_rsp_proto_rawDescData
}

var file_bs_rsp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bs_rsp_proto_goTypes = []any{
	(*ProtoResponse)(nil),         // 0: bs.ProtoResponse
	(*EndnodeAttachResponse)(nil), // 1: bs.EndnodeAttachResponse
	(*EndnodeDetachResponse)(nil), // 2: bs.EndnodeDetachResponse
	(*ErrorResponse)(nil),         // 3: bs.ErrorResponse
}
var file_bs_rsp_proto_depIdxs = []int32{
	1, // 0: bs.ProtoResponse.att_rsp:type_name -> bs.EndnodeAttachResponse
	2, // 1: bs.ProtoResponse.det_rsp:type_name -> bs.EndnodeDetachResponse
	3, // 2: bs.ProtoResponse.err:type_name -> bs.ErrorResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bs_rsp_proto_init() }
func file_bs_rsp_proto_init() {
	if File_bs_rsp_proto != nil {
		return
	}
	file_bs_rsp_proto_msgTypes[0].OneofWrappers = []any{
		(*ProtoResponse_AttRsp)(nil),
		(*ProtoResponse_DetRsp)(nil),
		(*ProtoResponse_Err)(nil),
	}
	file_bs_rsp_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bs_rsp_proto_rawDesc), len(file_bs_rsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bs_rsp_proto_goTypes,
		DependencyIndexes: file_bs_rsp_proto_depIdxs,
		MessageInfos:      file_bs_rsp_proto_msgTypes,
	}.Build()
	File_bs_rsp_proto = out.File
	file_bs_rsp_proto_goTypes = nil
	file_bs_rsp_proto_depIdxs = nil
}
